#
# Copyright (C) 2020-2023 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

COMMON_PATH := device/huawei/hi3650

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true
OVERRIDE_PRODUCT_COMPRESSED_APEX := false

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53

TARGET_BOARD_SUFFIX := _64
TARGET_IS_64_BIT := true

TARGET_BOARD_PLATFORM := hi3650
TARGET_BOARD_PLATFORM_GPU := Mali-T880
BOARD_VENDOR_PLATFORM := hi3650

# Bluetooth
BOARD_USES_LIBBT_WRAPPER := true

# Bootanimation
TARGET_BOOTANIMATION_HALF_RES := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := hi3650
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Build rules
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_USES_BUILD_COPY_HEADERS := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Charger 
BACKLIGHT_PATH := /sys/class/leds/lcd_backlight0/brightness

# Display
TARGET_ADDITIONAL_GRALLOC_10_USAGE_BITS := 0x2080000 | 0x2000000
TARGET_SCREEN_DENSITY := 420

# Encryption
TARGET_PROVIDES_KEYMASTER := true

# HIDL
DEVICE_MANIFEST_FILE := $(COMMON_PATH)/prebuilts/manifest.xml
DEVICE_MATRIX_FILE := $(COMMON_PATH)/prebuilts/compatibility_matrix.xml

# Kernel
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_BASE := 0x00478000
BOARD_KERNEL_CMDLINE := loglevel=6 page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M
BOARD_KERNEL_CMDLINE += loop.max_part=7
BOARD_KERNEL_CMDLINE += androidboot.super_partition=system
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x07b88000 --tags_offset 0x07588000
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_KERNEL_SOURCE := kernel/huawei/beethoven
TARGET_KERNEL_CONFIG := hi3650_defconfig
TARGET_KERNEL_CLANG_VERSION := r416183b
TARGET_KERNEL_CLANG_PATH := $(abspath .)/prebuilts/clang/kernel/$(HOST_PREBUILT_TAG)/clang-$(TARGET_KERNEL_CLANG_VERSION)
TARGET_KERNEL_LLVM_BINUTILS := false
TARGET_KERNEL_ADDITIONAL_FLAGS := \
    HOSTCFLAGS="-fuse-ld=lld -Wno-unused-command-line-argument"

# Lights
TARGET_PROVIDES_LIBLIGHT := true

# Metadata
BOARD_USES_METADATA_PARTITION := true

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_USERDATAIMAGE_PARTITION_SIZE := 26935787520 #(26935820288 - 32768)

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext

# Partitions - dynamic
BOARD_SUPER_PARTITION_BLOCK_DEVICES := cust patch product system vendor
BOARD_SUPER_PARTITION_CUST_DEVICE_SIZE ?= 201326592
BOARD_SUPER_PARTITION_PATCH_DEVICE_SIZE := 33554432
BOARD_SUPER_PARTITION_PRODUCT_DEVICE_SIZE ?= 201326592
BOARD_SUPER_PARTITION_SYSTEM_DEVICE_SIZE ?= 2080374784
BOARD_SUPER_PARTITION_VENDOR_DEVICE_SIZE ?= 637534208

BOARD_SUPER_PARTITION_SIZE := 3154116608
BOARD_SUPER_PARTITION_GROUPS := huawei_dynamic_partitions
BOARD_HUAWEI_DYNAMIC_PARTITIONS_PARTITION_LIST := odm system system_ext product vendor
BOARD_HUAWEI_DYNAMIC_PARTITIONS_SIZE := 3149922304 #( BOARD_SUPER_PARTITION_SIZE - 4 MB )
BOARD_SUPER_PARTITION_METADATA_DEVICE := system

BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 20971520 # 20MB
BOARD_VENDORIMAGE_PARTITION_RESERVED_SIZE := 20971520 # 20MB
# crDroid's system_ext/product are larger than LineageOS'; 640MB made the
# dynamic partitions exceed the 3149922304-byte group.
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 536870912 # 512MB
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE := 94371840 # 90MB
BOARD_ODM_EXTIMAGE_PARTITION_RESERVED_SIZE := 10485760 # 10MB

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USES_MKE2FS := true

BOARD_ROOT_EXTRA_FOLDERS :=  \
	sec_storage

# Props
TARGET_VENDOR_PROP += $(COMMON_PATH)/vendor.prop

# Recovery
TARGET_RECOVERY_FSTAB := $(COMMON_PATH)/rootdir/fstab.hi3650
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
BOARD_USES_FULL_RECOVERY_IMAGE := true

# Sepolicy
include device/huawei/compat/sepolicy/SEPolicy.mk
BOARD_VENDOR_SEPOLICY_DIRS += $(COMMON_PATH)/sepolicy/vendor
# The EMUI vendor blobs set and read platform properties and write legacy
# /data paths, which the Treble neverallows forbid. Only valid for userdebug.
SELINUX_IGNORE_NEVERALLOWS := true

# Vendor Init
TARGET_INIT_VENDOR_LIB := //$(COMMON_PATH):init_hisi
TARGET_RECOVERY_DEVICE_MODULES := init_hisi

# Vendor Security patch level
VENDOR_SECURITY_PATCH := 2024-06-05

# Verity - Only needed for signing
BOARD_AVB_ENABLE := false

# Vndk
PRODUCT_USE_VNDK_OVERRIDE := true
PRODUCT_FULL_TREBLE_OVERRIDE := true
PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE := true

# Vulkan
TARGET_USES_VULKAN := true

# Wifi
WPA_SUPPLICANT_VERSION		:= VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER	:= NL80211
BOARD_HOSTAPD_DRIVER		:= NL80211
CONFIG_DRIVER_NL80211		:= y
